// These styles apply to every route in the application
import './globals.css';
import {Providers} from "./providers";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className="bg-eggplant min-h-screen" >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}